---
default_language_version:
  python: python3.8
repos:
  # Fixing Python Files
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: env PYTHONPATH=. pylint
        language: system
        types: [python]

  # Fixing YAML Files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.11
    hooks:
      - id: yamlfmt
        exclude: example/conf/(logging)
        args: [--offset, '2', --mapping, '2', --sequence, '4']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]
